service: aws-lambda-crud-node
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-2:856536748046:table/TaskTable

functions:
  getTasks:
    handler: src/get-tasks.getTasks
    events:
      - httpApi:
          path: /tasks
          method: get
  createTask:
    handler: src/create-task.createTask
    events:
      - httpApi:
          path: /tasks
          method: post

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
